import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
//   // docusaurus.config.js

//   // exgenixSidebar: [
//   //   {
//   //     type: 'category',
//   //     label: 'Exgenix',
//   //     link: { type: 'doc', id: 'exgenix/exgenix' }, // Parent overview (index.md)
//   //     items: [
//   //       'exgenix/executive-overview',
//   //       'exgenix/qa-transformation-vision',
//   //       'exgenix/core-capabilities',
//   //       'exgenix/data-creation',
//   //       'exgenix/core-modules',
//   //       'exgenix/key-advantages',
//   //       'exgenix/value-propositions',
//   //     ],
//   //   },
//   // ],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };


const sidebars: SidebarsConfig = {
  tutorialSidebar: [

    {
      type: 'category',
      label: 'Exgenix',
      link: {
        type: 'doc',
        id: 'exgenix/exgenix'
      },
      description: 'The Exgenix platform revolutionizes QA for stock exchanges by integrating AI-driven test case generation, no-code automation, and comprehensive governance. Explore how Exgenix enhances test coverage, traceability, and efficiency across exchange systems.',
      // link: { type: 'doc', id: 'exgenix/exgenix' }, // parent doc
      items: [
        'exgenix/executive-overview',
        'exgenix/qa-transformation-vision',
        'exgenix/core-capabilities',
        'exgenix/data-creation',
        'exgenix/core-modules',
        'exgenix/key-advantages',
        'exgenix/value-propositions',
      ],
    },

    {
      type: 'category',
      label: 'Trial Access',
      // link: {
      //   type: 'generated-index',
      //   title: 'Trial Access',
      //   description: 'Get started with Exgenix through our Exgenix Trial. Explore core features, no-code automation, and AI-driven QA governance in a simulated exchange environment.',
      //   slug: '/trial-access'
      // },
      link: {
        type: 'doc',
        id: 'dbg-trial/dbg-trial', // points to docs/dbg-trial/index.md
      },
      items: [
        'dbg-trial/intro',
        'dbg-trial/purpose',
        'dbg-trial/governance-engine',
        'dbg-trial/no-code-automation',
        'dbg-trial/ai-qa-governance',
        'dbg-trial/what-to-expect',
        'dbg-trial/security',
        'dbg-trial/timeline',
        'dbg-trial/post-trial',
        'dbg-trial/commitment',
      ],
    },

    {
      type: 'category',
      label: 'Quick Started Guide',
      link: {
        type: 'doc',
        id: 'quick-start-guide/quick-start-guide', // points to quick-start-guide/index.md
      },
      // link: {
      //   type: 'generated-index',
      //   title: 'Exgenix Quick Start Guide (Trial Access)',
      //   description: 'Welcome to the Exgenix + AI QA Agent ecosystem! This Quick Start Guide provides your access details, project references, and navigation steps to help you start exploring the product immediately.',
      //   slug: '/quick-start-guide'
      // },
      items: [
        'quick-start-guide/access_credentials',
        'quick-start-guide/trial_project_details',
        'quick-start-guide/recommended_first_steps',
      ],
    },
    {
      type: 'category',
      label: 'AI Powered Testcase Generation',
      link: {
        type: 'doc',              // Link directly to index.md
        id: 'ai-powered-testcase-generation/ai-powered-testcase-generation', // your folder's index.md
      },
      items: [
        'ai-powered-testcase-generation/overview',
        'ai-powered-testcase-generation/category1',
        'ai-powered-testcase-generation/category2',
        'ai-powered-testcase-generation/category3',
        'ai-powered-testcase-generation/key-highlight',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'AI Powered Testcase Generation',
    //   link: {
    //     type: 'generated-index',
    //     title: 'AI-Powered Test Case Generation',
    //     description: 'Generate Testcase with use of AI from various sources like BRD, API Specs or User Stories.',
    //     slug: '/ai-powered-testcase-generation'
    //   },
    //   items: [
    //     'ai-powered-testcase-generation/overview',
    //     'ai-powered-testcase-generation/category1',
    //     'ai-powered-testcase-generation/category2',
    //     'ai-powered-testcase-generation/category3',
    //     'ai-powered-testcase-generation/key-highlight',
    //   ],
    // },

    {
      type: 'category',
      label: 'API Configuration',
      link: { type: 'doc', id: 'api-configuration/index' },
      items: [
        'api-configuration/overview',
        'api-configuration/module-structure',
        'api-configuration/collections',
        'api-configuration/api-configuration',
        'api-configuration/datasheets',
        'api-configuration/advanced-features',
        'api-configuration/best-practices',
        'api-configuration/troubleshooting',
        'api-configuration/summary',
      ],
    },

    {
  type: 'category',
  label: 'Test Action Unit',
  link: {
    type: 'doc',
    id: 'test-action-unit/test-action-unit',   // Your index.md for this section
  },
  items: [
    'test-action-unit/overview',
    'test-action-unit/what-is-tau',
    'test-action-unit/structure',
    'test-action-unit/creating-tau',
    'test-action-unit/example',
    'test-action-unit/datasheet-configuration',
    'test-action-unit/using-tau',
    'test-action-unit/common-patterns',
    'test-action-unit/best-practices',
    'test-action-unit/managing-tau',
    'test-action-unit/advanced-features',
    'test-action-unit/troubleshooting',
    'test-action-unit/summary',
  ],
},

{
  type: 'category',
  label: 'Test Case Configuration',
  link: {
    type: 'doc',
    id: 'test-case-configuration/test-case-configuration',   // points to index.md
  },
  items: [
    'test-case-configuration/overview',
    'test-case-configuration/module-structure',
    'test-case-configuration/test-cases',
    'test-case-configuration/creating-test-case',
    'test-case-configuration/step-settings',
    'test-case-configuration/advanced-features',
    'test-case-configuration/best-practices',
    'test-case-configuration/managing-test-cases',
    'test-case-configuration/common-scenarios',
    'test-case-configuration/troubleshooting',
    'test-case-configuration/summary',
  ],
},
{
  type: 'category',
  label: 'Test Suite Execution',
  link: {
    type: 'doc',
    id: 'test-suite-execution/test-suite-execution',   // points to index.md
  },
  items: [
    'test-suite-execution/overview',
    'test-suite-execution/module-structure',
    'test-suite-execution/components',
    'test-suite-execution/creating-collections',
    'test-suite-execution/creating-test-suites',
    'test-suite-execution/information-panel',
    'test-suite-execution/executing-suites',
    'test-suite-execution/execution-monitoring',
    'test-suite-execution/reports',
    'test-suite-execution/scheduled-execution',
    'test-suite-execution/managing-suites',
    'test-suite-execution/best-practices',
    'test-suite-execution/troubleshooting',
    'test-suite-execution/summary',
  ],
},




    // 'api-configuration',
    // 'test-action-unit',
    // 'testcase',
    // 'test_suite_and_execution',
    // {
    //   type: 'category',
    //   label: 'Sample Test Scenario',
    //   link: {
    //     type: "generated-index",
    //     description: "This section contains multiple test scenarios.",
    //   },
    //   items: [
    //     "sample-test-scenario/scenario_1",
    //     "sample-test-scenario/scenario_2",
    //   ],
    // },

    {
      type: 'category',
      label: 'Sample Test Scenario',
      link: {
        type: 'doc',             // Direct link to index.md
        id: 'sample-test-scenario/sample-test-scenario',
      },
      items: [
        'sample-test-scenario/scenario_1',
        'sample-test-scenario/scenario_2',
      ],
    },

    // {
    //   type: 'category',
    //   label: 'AI QA Agent',
    //   link: { type: 'doc', id: 'ai-qa-agent' }, // parent doc
    //   items: [
    //     'ai-qa-agent/usecase1',
    //     'ai-qa-agent/usecase2',
    //     'ai-qa-agent/usecase3',
    //   ],
    // },

    {
  type: 'category',
  label: 'AI QA Agent',
  link: {
    type: 'doc',
    id: 'ai-qa-agent/ai-qa-agent',   // Your index page
  },
  items: [
    'ai-qa-agent/overview',
    'ai-qa-agent/key-features',
    'ai-qa-agent/qa-governance-benefits',
    'ai-qa-agent/value-propositions',
    'ai-qa-agent/integration-ecosystem',
    'ai-qa-agent/target-audience',
    'ai-qa-agent/complete-workflow',
    'ai-qa-agent/continuous-learning',
    'ai-qa-agent/success-metrics',
    'ai-qa-agent/technical-capabilities',
    'ai-qa-agent/security-compliance',
    'ai-qa-agent/getting-started',
        'ai-qa-agent/usecase1',
        'ai-qa-agent/usecase2',
        'ai-qa-agent/usecase3',
  ],
},


    'contact-us',

    // ✅ Add Exgenix as a nested category here

  ],
};

// module.exports = {
//   docs: [
//     {
//       type: 'category',
//       label: 'Videos',
//       collapsible: false,
//       items: ['videos/videos'], // <-- Point to our videos page
//     },
//   ],
// };


export default sidebars;


// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   docs: [
//     // your main docs auto sidebar (optional)
//     { type: 'autogenerated', dirName: '.' },

//     // Videos section
//     {
//       type: 'category',
//       label: 'Videos',
//       collapsible: false,
//       items: ['videos/videos'], // points to docs/videos/videos.md
//     },
//   ],
// };

// export default sidebars;



// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   docs: [
//     { type: 'autogenerated', dirName: '.' },

//     {
//       type: 'category',
//       label: 'Videos',
//       collapsible: false,
//       items: ['videos'],
//     },
//   ],
// };

// export default sidebars;

