import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
//   // docusaurus.config.js

//   // exgenixSidebar: [
//   //   {
//   //     type: 'category',
//   //     label: 'Exgenix',
//   //     link: { type: 'doc', id: 'exgenix/exgenix' }, // Parent overview (index.md)
//   //     items: [
//   //       'exgenix/executive-overview',
//   //       'exgenix/qa-transformation-vision',
//   //       'exgenix/core-capabilities',
//   //       'exgenix/data-creation',
//   //       'exgenix/core-modules',
//   //       'exgenix/key-advantages',
//   //       'exgenix/value-propositions',
//   //     ],
//   //   },
//   // ],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };


const sidebars: SidebarsConfig = {
  tutorialSidebar: [

    {
      type: 'category',
      label: 'Exgenix',
      link: { type: 'doc', id: 'exgenix/exgenix' }, // parent doc
      items: [
        'exgenix/executive-overview',
        'exgenix/qa-transformation-vision',
        'exgenix/core-capabilities',
        'exgenix/data-creation',
        'exgenix/core-modules',
        'exgenix/key-advantages',
        'exgenix/value-propositions',
      ],
    },

    // ✅ Keep your existing docs as they are
    'quick-start-guide',
    'ai-powered-testcase-generation',
    'api-configuration',
    'test-action-unit',
    'testcase',
    'test_suite_and_execution',
    {
      type: 'category',
      label: 'Sample Test Scenario',
      link: { type: 'doc', id: 'sample_test_scenario' }, // parent doc
      items: [
      'sample-test-scenario/scenario_1',
      'sample-test-scenario/scenario_2',
      ],
    },
    {
      type: 'category',
      label: 'AI QA Agent',
      link: { type: 'doc', id: 'ai-qa-agent' }, // parent doc
      items: [
      'ai-qa-agent/usecase1',
      'ai-qa-agent/usecase2',
      'ai-qa-agent/usecase3',
      ],
    },
    
    
    
    'contact-us',

    // ✅ Add Exgenix as a nested category here
    
  ],
};

// module.exports = {
//   docs: [
//     {
//       type: 'category',
//       label: 'Videos',
//       collapsible: false,
//       items: ['videos/videos'], // <-- Point to our videos page
//     },
//   ],
// };


export default sidebars;


// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   docs: [
//     // your main docs auto sidebar (optional)
//     { type: 'autogenerated', dirName: '.' },

//     // Videos section
//     {
//       type: 'category',
//       label: 'Videos',
//       collapsible: false,
//       items: ['videos/videos'], // points to docs/videos/videos.md
//     },
//   ],
// };

// export default sidebars;



// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   docs: [
//     { type: 'autogenerated', dirName: '.' },

//     {
//       type: 'category',
//       label: 'Videos',
//       collapsible: false,
//       items: ['videos'],
//     },
//   ],
// };

// export default sidebars;

