import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // docusaurus.config.js


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

// module.exports = {
//   docs: [
//     {
//       type: 'category',
//       label: 'Videos',
//       collapsible: false,
//       items: ['videos/videos'], // <-- Point to our videos page
//     },
//   ],
// };


export default sidebars;


// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   docs: [
//     // your main docs auto sidebar (optional)
//     { type: 'autogenerated', dirName: '.' },

//     // Videos section
//     {
//       type: 'category',
//       label: 'Videos',
//       collapsible: false,
//       items: ['videos/videos'], // points to docs/videos/videos.md
//     },
//   ],
// };

// export default sidebars;



// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   docs: [
//     { type: 'autogenerated', dirName: '.' },

//     {
//       type: 'category',
//       label: 'Videos',
//       collapsible: false,
//       items: ['videos'],
//     },
//   ],
// };

// export default sidebars;

